config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'landing#index'

  resources :users do
    get :ravelries
  end

  resources :ravelries
  

  get "/search" => "ravelries#search"
  # put "/patterns/index" => "ravelries#add_pattern"
  # post "/search" => "ravelries#search"
  get "/mypatterns" => "users#patterns" 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  belongs_to :user
  belongs_to :ravelry


  

end

app/models/ravelry.rb
class Ravelry < ApplicationRecord
  has_many :patterns
  has_many :users, through: :patterns

  validates :pattern_name, presence: true
  validates :ravelry_id, presence: true
  validates :web_link, presence: true
  validates :picture, presence: true

  # def self.search(search)
  #   if search
  #     searched_pattern = Ravelry.find_by(pattern_name: search)
  #       if searched_pattern
  #         self.where(id: searched_pattern)
  #       else
  #         @patterns = Ravelry.all
  #       end
  #   else
  #     @patterns = Ravelry.all
  #   end
  # end

  # scope :search, -> (name_parameter) { where("name ilike ?", "%#{name_parameter}%")}

end

app/models/ravelryuser.rb
class RavelryUser < ApplicationRecord
  belongs_to :user
  belongs_to :ravelry
end

app/models/search.rb
class Search <ApplicationRecord

  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :patterns
  has_many :ravelries, through: :patterns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    if current_user != nil
      @user = current_user
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    if current_user != nil
      @user = current_user
    end
  end
end

app/controllers/layout_controller.rb
class LayoutsController < ApplicationController

  def application
    @user = User.find(params[:user_id])
    render :application
  end

end

app/controllers/old_patterns_controller.rb
class PatternsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @pattern = @user.pattern
    render: index
  end

  def new
    @user = User.find(params[:user_id])
    @pattern = @user.patterns.new
    render :new
  end

  def edit
    @user = User.find(params[:user_id])
    @pattern = Pattern.find(params[:id])
    render :edit
  end

  private
  def pattern_params
    params.require(:pattern).permit(:pattern_name, :picture, :web_link, :user_id, :craft_type, :ravelry_id)

end

app/controllers/ravelries_controller.rb
class RavelriesController < ApplicationController

  def index
    # @user = User.find(params[:user_id])
    @patterns = Ravelry.all
    @user = current_user
  end

  def search
    # if params[:pattern_name]
    #   @searched_pattern = Ravelry.where('pattern_name ILIKE ?', "%#{params[:pattern_name]}%")
    # else
      # @patterns = Ravelry.all
    # @patterns = Ravelry.search(params[:search])
    # if current_user != nil
    #   @user = current_user
    # end
    # redirect_to new_user_pattern_path(@user)
    @user = current_user
    if params[:search].blank?
      redirect_to search_path and return
    else
      @parameter = params[:search]
      @results = Ravelry.all.where("lower(pattern_name) ilike :search", search: "%#{@parameter}%")
    end
  end

  def update
    @user = User.find(params[:user_id])
    @ravelry = Ravelry.find(params[:id])
  end

  def show
    @patterns = Ravelry.all
    render :show
  end

  # def add_pattern
  #   puts "test"
  #   # @user = current_user
  #   # @ravelry = Ravelry.find(params[:id])
  #   # @user.ravelries << @ravelry
  #   # flash[:notice] = 'Pattern was saved.'
  #   # redirect_to user_path(@user)
  # end

  def create
    @user = current_user
    @ravelry = Ravelry.find(params[:id])
    @user.ravelries << @ravelry
    flash[:notice] = 'Pattern was saved.'
  end

  private

  def ravelry_params
    params.require(:ravelry).permit(:pattern_name, :ravelry_id, :search, :id)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def patterns
  #   @user = User.find(params[:id])
  #   @patterns = RavelryUser.find_by(@user.id)
  #   render :patterns
  # end

  # def show
    @user = current_user
    @patterns = Pattern.where(:user_id => @user.id)
  end

end

app/controllers/users_ravelries_controller.rb
class UsersRavelriesController < ApplicationController

  def create
    user = User.find(params:[user_id])
    ravelry_ids = params[:ravelry_ids]
    user.ravelries = Ravelry.find(ravelry_ids)
    redirect_to user_path
  end

  private

  def user_ravelry_params
    params.require(:user_ravelry).permit(:user_id, :ravelry_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<div class="jumbotron">
<h1>Daily Dose of Fiber Crafts</h1>
</div>

<% unless current_user %>
<%= link_to 'Please Sign In', '/users/sign_in', class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily Dose of Fiber Crafts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body class="container">
    <nav class="navbar navbar-expand-md">
      <div class="container-fluid">
        <a class="navbar-brand abs" href="/">Daily Dose of Fiber Crafts</a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <%= link_to 'All Patterns', ravelries_path, class: "nav-link" %>
            </li>
            <% if current_user %>
            <li class="nav-item">
              <%= link_to 'My Saved Patterns', '/mypatterns', class: "nav-link" %>
              </li>
              <li class="nav-item">
              <%= link_to "Sign Out", '/users/sign_out', :method => :delete, class: "nav-link" %>
            </li>
            <% else %>
            <li>
              <%= link_to "Sign up", '/users/sign_up', class: "nav-link" %> <% link_to "Sign in", '/users/sign_in' %>
            </li>
            <% end %>
            <li class="nav-item">
              <%= form_tag(search_path, :class => "form-inline my-2 my-lg-0", :method => "get") do %>
            </li>
                <li>
                  <%= search_field_tag :search, params[:search], placeholder: "Search for patterns", class: "form-control mr-sm-2" %>
                </li>
                <li>
                  <%= button_tag "Search", :class => "btn btn-primary", :pattern_name => nil %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>   
    <%= yield %>
  </body>
</html>

app/views/ravelries/index.html.erb
<h1> All Patterns </h1>

<div class="row">
<% @patterns.each do |r| %>
    <div class="col-sm-2">
      <div class="card">
        <img class="card-img-top" src=<%=r.picture%> alt=<%r.pattern_name%>>
        <div class="card-body">
          <h5 class="card-title"><%= r.pattern_name %></h5>
          <a class="card-text" href="http://www.ravelry.com/patterns/library/<%= r.web_link %>">View on Ravelry</a>
          
          <%# <%= button_to "Create", {action: "create" },  [:%>  
          <%= button_to "Save Pattern", class: "btn btn-primary", :method => :post, :params => {:id => r.id} %>


        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/ravelries/search.html.erb
<div class="row">
<h4>Search Results</h2>
</div>
<br>

<div class="row">
  <% @results.each do |r| %>
    <div class="col-sm-2">
      <div class="card">
        <img class="card-img-top" src=<%=r.picture%> alt=<%r.pattern_name%>>
        <div class="card-body">
          <h5 class="card-title"><%= r.pattern_name %></h5>
          <a class="card-text" href="http://www.ravelry.com/patterns/library/<%= r.web_link %>">View on Ravelry</a>
          
          <%= button_to "Save Pattern", :method => :post, :action => :create, :params => {:id => r.id} %>
        </div>
      </div>
    </div>
  <% end %>
</div>
  

app/views/ravelries/show.html.erb
<h1> All Patterns </h1>

<%= else @patterns.each do |r| %>
    <div class="col-sm-2">
      <div class="card">
        <img class="card-img-top" src=<%=r.picture%> alt=<%r.pattern_name%>>
        <div class="card-body">
          <h5 class="card-title"><%= r.pattern_name %></h5>
          <a class="card-text" href="http://www.ravelry.com/patterns/library/<%= r.web_link %>">View on Ravelry</a>
          
          <%# <%= button_to "Create", {action: "create" },  [:%>  
          <button class="btn btn-sm btn-primary" value="1" name="ravelry[user_id]" id="ravelry_user_ids_1">Add to Pattern List</button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/patterns.html.erb
<h1> My Saved Patterns </h1>

<div class="row">
<% @patterns.each do |r| %>
    <div class="col-sm-2">
      <div class="card">
        <img class="card-img-top" src=<%=r.ravelry.picture%> alt=<%r.ravelry.pattern_name%>>
        <div class="card-body">
          <h5 class="card-title"><%= r.ravelry.pattern_name %></h5>
          <a class="card-text" href="http://www.ravelry.com/patterns/library/<%= r.ravelry.web_link %>">View on Ravelry</a>
        </div>
      </div>
    </div>
  <% end %>
</div>